### ISSUE TITLE
Playback won't start.

### ISSUE THREAD

**Issue by whiteonred** [Xxathyx/MediaPlayer#6]
Hello! Any ideas why my video won't start playing? I'm following the instructions, there are no errors in the console, but the first frame just hangs like this and doesn't change at all....

Example: https://youtu.be/xRY7Xuacgmo

Self-hosted server in Pterodactyl on my local network, kernel purple 1.21 (via bungeecord).

**Comment by Xxathyx** [comment]
Hello,

This is a known problem due to an integer representation when I introduced audio delay in the last update ... I updated the plugin to do a hotfix, you can update it and tell me how it goes. Thanks!

**Comment by whiteonred** [comment]
Tried the new version.

Installed the update.
Deleted the previous video data.
Started the video "load" again.
After the loading was complete, I played the video according to the instructions.

Unfortunately, the system behavior did not change, and playback also starts and continues with 0 FPS.

![Image](https://github.com/user-attachments/assets/b6803c97-cb9b-4fcf-8d61-521d94207482)

**Comment by Xxathyx** [comment]
Hello, a quick fix would be to specify your server-ip, set server-ip=192.168.0.2 in your server.properties, because by default it is empty.

**Comment by whiteonred** [comment]
I tested this option, unfortunately it doesn't work. The server inside Docker always starts at 0.0.0.0 and forcibly overwrites the server-ip parameter in server.properties. As a result, the datapack still tries to download from 0.0.0.0, which of course doesn't work.

![Image](https://github.com/user-attachments/assets/c9563e37-6baa-4a78-a001-8ebeb9b834c5)

**Comment by whiteonred** [comment]
Sorry for the delay!

Here are the logs from the latest version 1.21.4
Plugin version 1.0.2, overall the problem is still relevant.

Client logs at the time of downloading the datapack are here: https://pastes.dev/SubFXIcOgs

Let me remind you that I have a local server and I connect to the address 192.168.0.2, but for some reason the resource packs are trying to download from 0.0.0.0.

Thanks

**Comment by Xxathyx** [comment]
Hello,

The plugin just has been update, as of now you can edit the `plugin.alternative-server` field in the configuration file, the problem is that the issue you are showing is very specific to your machine, so if the `plugin.alternative-server` is different from `none` it will download the datapack from the specified adress instead of the auto-detected one. So you can update the plugin and insert `192.168.0.2` in this field.

Thanks

**Comment by whiteonred** [comment]
![Image](https://github.com/user-attachments/assets/dfea1913-23f2-4fbd-9f20-38baafe9cbbe)

Thanks for the fix, I tried this option, I managed to change the IP, but it didn't change the situation completely, the error in the console is the same, it's impossible to download. There are ideas that this is because of a random port that is closed in the docker container.. Is it possible to make some port that can be specified and it was static? For example 25568...

**Comment by Xxathyx** [comment]
I updated a bit the code, now the `plugin.alternative-server field` also take the port, so if you insert `192.168.0.2:25568` in that field, the temporary host for datapack will be there.

**Comment by whiteonred** [comment]
IT WORKS! Now I and all the players on the server can hear the sound, thank you very much for the quick help. I offer a small guide for those who will try to run video on a server created through the server control panel on Docker.

> 1. Add to the alternative-server config: public server IP and a separate port for downloading the audio data package in the format 192.184.1.5:25565;
> 2. Open the port for the public internet (ufw+router etc.);
>
